[env:lilygo-t5-47-s3]
platform = espressif32@6.4.0
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
lib_deps =
    bblanchon/ArduinoJson@^6.21.3
    bodmer/TJpg_Decoder@^1.1.0
    bitbank2/PNGdec@^1.0.1
    lennarthennigs/Button2@^2.3.2
    ricmoo/QRCode@^0.0.1
    lewisxhe/PCF8563_Library@^1.0.1
    lewisxhe/SensorLib@^0.2.0
build_flags =
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D LILYGO_T5_47_S3
    -D PNG_MAX_BUFFERED_PIXELS=1024